/**
 * SuperC Bitflags defines...
 *
 *
 */

.ifndef _BFLAGS_INC
.define _BFLAGS_INC

;------------------------------------------------
; Track bit flags define
;------------------------------------------------
.define		TRKFLG_PORTAM	$80
.define		TRKFLG_ECHO	$40
.define		TRKFLG_NOISE	$20
.define		TRKFLG_HWPMON	$10
.define		TRKFLG_NKOF	$08
;.define	XXXXX		$04
;.define	XXXXX		$02
.define		TRKFLG_TIE	$01
; bit1~bit3 ... not use



.endif

