/**
 * SuperC
 *
 *
 */

.ifndef _VAR_INC
.define _VAR_INC

;------------------------------------------------
; DEFINE
;------------------------------------------------

;-- spc core
.define DIR	$30
.define ESA	$80
.define TIMER	16	; Nintendo
;.define TIMER	40	; Standard

;-- spc engine
.define SND_TEMPO            56
;.define MUSIC_TEMPO_DEFAULT  54
.define MUSIC_TEMPO_DEFAULT  10
.define SPECIAL_WAV_FREQ 16

.endif

